# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/MIDI-Player-and-ADC.runs/synth_1/music_adc_top_level.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/MIDI-Player-and-ADC.cache/wt [current_project]
set_property parent.project_path C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/MIDI-Player-and-ADC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/MIDI-Player-and-ADC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/adc_averager.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/averager.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/basys_display.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/bin_to_bcd.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/music_player_stuff/buzzer_pwm.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/buzzer_volume.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/digit_multiplexor.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/music_player.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/muxS_W.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/mydowncounter.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/music_player_stuff/note_to_period.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/pwm.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/pwm_adc.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/pwm_adc_sar.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/pwm_adc_sweep.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/r2r_adc.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/r2r_adc_sar.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/r2r_adc_sweep.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/scalar.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/scaling_calibrator.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/seven_segment_decoder.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/seven_segment_digit_selector.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/seven_segment_display_subsystem.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song0_dur.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song0_pitch.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song1_dur.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song1_pitch.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song2_dur.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song2_pitch.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song3_dur.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song3_pitch.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song4_dur.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song4_pitch.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song5_dur.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song5_pitch.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song6_dur.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song6_pitch.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song7_dur.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/songs/song7_pitch.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/music_player_stuff/song_player_timer.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/switch_assignment.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/synchronizer.sv
  C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/music_adc_top_level.sv
}
read_ip -quiet c:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/MIDI-Player-and-ADC.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/MIDI-Player-and-ADC.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/MIDI-Player-and-ADC.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/Basys3_music_adc_contraints.xdc
set_property used_in_implementation false [get_files C:/Users/vikra/Documents/SyncedProjects/FPGA-MIDI-Player/MIDI-Player-and-ADC/Basys3_music_adc_contraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top music_adc_top_level -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef music_adc_top_level.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file music_adc_top_level_utilization_synth.rpt -pb music_adc_top_level_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
